#pragma once

#include <cstdint>

// Included by the generated ppc_config.h when PPC_INCLUDE_DETAIL is defined
// (see MarathonRecompLib/CMakeLists.txt). This file is tracked in git; the
// rest of ppc/ is generated by XenonRecomp and ignored.

struct PPCContext;

// Out-of-line handler for indirect calls whose target is not a recompiled
// function. Logs (rate-limited) and returns, turning a guaranteed wild jump
// into a skipped call. Defined in MarathonRecomp/kernel/memory.cpp.
extern "C" void PPCIndirectCallMissing(PPCContext& ctx, uint8_t* base, uint32_t target);

// On some devices the game evaluates a half-constructed animation subtree;
// visitors then fetch vtables from guest null (reads absorbed by the readable
// guest null page, see kernel/memory.cpp) and call through method pointer 0.
// The stock macro dereferences the function table unconditionally, which for
// such targets reads far outside the table and jumps to garbage.
// Validate the target range and the resolved host pointer instead of crashing.
// The valid range spans to the image end, not just the code section: kernel import
// thunks live directly after the code (first at exactly PPC_CODE_BASE+PPC_CODE_SIZE)
// and are registered into the function table by Memory::InsertFunction.
// Do not rely on unsigned range subtraction here. A corrupted guest
// vtable/function pointer such as 0x00000002 would otherwise be easy to
// misclassify if the generated constants change type or base. PPC code targets
// must be aligned and inside the actual image interval.
#define PPC_CALL_INDIRECT_FUNC(x) \
    do \
    { \
        const uint32_t ppcCallTarget_ = (uint32_t)(x); \
        const uint64_t ppcTarget_ = ppcCallTarget_; \
        const uint64_t ppcImageBegin_ = PPC_CODE_BASE; \
        const uint64_t ppcImageEnd_ = PPC_IMAGE_BASE + PPC_IMAGE_SIZE; \
        PPCFunc* ppcCallFn_ = \
            (ppcTarget_ >= ppcImageBegin_ && \
             ppcTarget_ < ppcImageEnd_ && \
             (ppcCallTarget_ & 3u) == 0) \
                ? PPC_LOOKUP_FUNC(base, ppcCallTarget_) \
                : nullptr; \
        if (ppcCallFn_ != nullptr) \
            ppcCallFn_(ctx, base); \
        else \
            PPCIndirectCallMissing(ctx, base, ppcCallTarget_); \
    } while (0)
